# Generated by Django 3.0.2 on 2020-01-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img_path',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
